# Generated by Django 2.2.1 on 2019-06-19 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_auto_20181002_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='valid_until',
            field=models.DateField(default=datetime.date(2019, 7, 1), verbose_name='Valid Until'),
        ),
    ]
